//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds178346566_dbEntities : DbContext
    {
        public qds178346566_dbEntities()
            : base("name=qds178346566_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WXL_Article> WXL_Article { get; set; }
        public virtual DbSet<WXL_Tag> WXL_Tag { get; set; }
        public virtual DbSet<WXL_Users> WXL_Users { get; set; }
        public virtual DbSet<WXL_MENU> WXL_MENU { get; set; }
        public virtual DbSet<WXL_RoleMenu_Mid> WXL_RoleMenu_Mid { get; set; }
        public virtual DbSet<WXL_Role> WXL_Role { get; set; }
        public virtual DbSet<WXL_UserMenu_Mid> WXL_UserMenu_Mid { get; set; }
        public virtual DbSet<WXL_UserRole_Mid> WXL_UserRole_Mid { get; set; }
    }
}
