//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXL_Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string ContentTxt { get; set; }
        public int Type1 { get; set; }
        public string Type2 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime AlterTime { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public decimal LookNum { get; set; }
        public string Abstract { get; set; }
        public int Isdel { get; set; }
        public string ArticleId2 { get; set; }
    }
}
